#
# This file is part of Mobile Robot Framework.
# Mobile Robot Framework is free software under the terms of GNU AFFERO GENERAL PUBLIC LICENSE.
#
sudo: required

services:
  - docker

language: node_js
node_js:
  - "6.0.0"

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - npm install -g copyfiles
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js
  - docker pull mobilerobotframework/app
  - npm run build:with-downloads
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - npm run docker:build
  - npm run docker:push

notifications:
  slack: mobilerobotframework:W3tBJqXBF4nYgnoP8q3tAcmp
